<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter
   

In [90]:
import pandas as pd
import psycopg2
import numpy as np
from sqlalchemy import select

In [91]:
# вставьте сюда параметры подключения из юнита 1. Работа с базой данных из Python 

DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [92]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies). 

In [10]:
# текст запроса
query_3_1 = f'''select count(id)
            from vacancies
'''


In [11]:
# результат запроса
df_3_1 = pd.read_sql_query(query_3_1, connection)
df_3_1
# Количество вакансий в нашей базе = 49197

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/3713039602.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3_1 = pd.read_sql_query(query_3_1, connection)


count
0  49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers). 

In [12]:
query_3_2 = f'''select count(distinct id)
            from employers
'''

In [13]:
# результат запроса
df_3_2 = pd.read_sql_query(query_3_2, connection)
df_3_2
# Количество работодателей = 23501

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/2994483377.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3_2 = pd.read_sql_query(query_3_2, connection)


count
0  23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [50]:
# текст запроса
query_3_3 = f'''select count(id)
from areas
'''

In [51]:
# результат запроса
df_3_3 = pd.read_sql_query(query_3_3, connection)
df_3_3
# Количество регионов = 1362.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/3729486151.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3_3 = pd.read_sql_query(query_3_3, connection)


count
0   1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [16]:
# текст запроса
query_3_4 = f'''select count(id)
from industries
'''

In [17]:
# результат запроса
df_3_4 = pd.read_sql_query(query_3_4, connection)
df_3_4
# Сфер деятельности 394.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/822032040.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_3_4 = pd.read_sql_query(query_3_4, connection)


count
0    294

In [166]:
# Для того, чтобы сделать выводы по предварительному анализу данных, посмотрим на данные о том, 
# сколько вакансий предлагает каждая компания и в каком регионе.  
 
query_vacancies = f'''select e.name as employer, a.name as area, count(v.id) vac_cnt
from vacancies v 
join areas a on v.area_id = a.id
join employers e on v.employer_id = e.id
GROUP BY e.name, a.name
ORDER BY vac_cnt desc
LIMIT 60
'''

result_vac = pd.read_sql(query_vacancies, connection)
result_vac

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_8714/2253290460.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_vac = pd.read_sql(query_vacancies, connection)


employer              area  \
0                                                СБЕР            Москва   
1                                             DataArt            Алматы   
2                                             DataArt        Нур-Султан   
3                                                 МТС            Москва   
4                                       Газпром нефть   Санкт-Петербург   
5                                                  VK            Москва   
6                                                Ozon            Москва   
7                              МАГНИТ, Розничная сеть         Краснодар   
8                                              Яндекс            Москва   
9                             Лига Цифровой Экономики            Москва   
10                                           Тинькофф            Москва   
11                                        ARRIVAL LTD           Тбилиси   
12                                  DNS Головной офис       Владивосток   
13                                    Bell Integrator           Саратов   
14                                       Ак Барс Банк            Казань   
15                                        Beeline, ТМ            Алматы   
16                                         Альфа-Банк            Москва   
17                           Иннотех, Группа компаний            Москва   
18                                           СофтКорп             Минск   
19                                           Тинькофф   Нижний Новгород   
20                                       Вайзор Геймз             Минск   
21                                             Яндекс   Санкт-Петербург   
22                                                 VK   Санкт-Петербург   
23                              Совкомбанк Технологии       Новосибирск   
24                                     Банк ВТБ (ПАО)            Москва   
25                                             Яндекс      Екатеринбург   
26                                      Газпром нефть              Омск   
27                                         UNITEL LLC           Ташкент   
28                                             Тензор         Ярославль   
29                                             Яндекс   Нижний Новгород   
30                                      Газпром нефть            Тюмень   
31                                        Itransition           Тбилиси   
32                                          SOFTSWISS           Тбилиси   
33                                             Яндекс       Новосибирск   
34                                         Ростелеком         Краснодар   
35                                           Andersen           Армения   
36                        Центр финансовых технологий       Новосибирск   
37                                              КАМАЗ  Набережные Челны   
38                            Банк Хоум Кредит, ДБ АО            Алматы   
39                                              Tele2    Ростов-на-Дону   
40                                        ИК СИБИНТЕК           Саратов   
41                                        ИК СИБИНТЕК            Самара   
42                                             Яндекс           Воронеж   
43                                        АйСи Сервис       Симферополь   
44                                             Контур      Екатеринбург   
45                                                МТС         Краснодар   
46                                           Andersen            Алматы   
47  Мобайл Телеком-Сервис (Объединенная Компания T...            Алматы   
48                                           ИнфоТеКС             Томск   
49                              Совкомбанк Технологии            Казань   
50                                               СБЕР   Нижний Новгород   
51  КБ Уральский банк реконструкции и развития (УБ...      Екатеринбург   
52                                               СБЕР       Новосибирс

Выводы по предварительному анализу данных:
Данные в таблицах о вакансиях, регионах, работодателях связаны между собой по ключевым столбцам (id), что делает возможным комбинирование данных удобным для анализа образом.
Говоря о взаимосвязи данных, можно отметить, что количество работодателей (23 501) меньше количества предлагаемых вакансий (49 197) более чем в два раза. 
Однако, распределение вакансий относительно работодателей неравномерно: 
например, налоговая служба в Нижнем Новгороде разместила предложение об одной свободной вакансии, 
в то время как Сбербанк в г. Москва разместил на hh 205 вакансий.
Следовательно, можно сказать об очевидной зависимости количества вакансий от масштаба компании и численности населения города, в котором требуется определенный специалист. 


***

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [20]:
# текст запроса
query_4_1 = f'''SELECT
    count(vacancies.id) as cnt, areas.name as area
FROM
    vacancies left join areas on vacancies.area_id = areas.id
GROUP BY areas.name
ORDER BY count(vacancies.id) desc'''


In [21]:
# результат запроса
cnt = pd.read_sql_query(query_4_1, connection)
cnt
# В результате выполнения запроса в ячейке выше, увидим, 
# что топ 5 городов по количеству вакансий: Москва, Санкт-Петербург, Минск, Новосибирск, Алматы.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/3869464411.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cnt = pd.read_sql_query(query_4_1, connection)


cnt             area
0    5333           Москва
1    2851  Санкт-Петербург
2    2112            Минск
3    2006      Новосибирск
4    1892           Алматы
..    ...              ...
764     1       Тарко-Сале
765     1    Новоаннинский
766     1            Бирск
767     1           Сасово
768     1             Анна

[769 rows x 2 columns]

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [22]:
# текст запроса
query_4_2 = f'''SELECT 
    count(vacancies.id)
FROM 
    vacancies
WHERE salary_from is not null or salary_to is not null
'''

In [23]:
# результат запроса = 24073 вакансии, в которых указана хотя бы одна граница заработной платы
result_4_2 = pd.read_sql_query(query_4_2, connection)
result_4_2

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/4179562550.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_4_2 = pd.read_sql_query(query_4_2, connection)


count
0  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [24]:
# текст запроса
query_4_3 = f'''SELECT 
    round(AVG(salary_from)) as "Среднее значение для нижней границы зп",
    round(AVG(salary_to)) as "Среднее значение для верхней границы зп"
FROM
    vacancies
    '''

In [25]:
# результат запроса: Среднее значение для нижней границы зп = 71 065; 
# Среднее значение для верхней границы зп = 110 537.
result_4_3 = pd.read_sql_query(query_4_3, connection)
result_4_3

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/2521755017.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_4_3 = pd.read_sql_query(query_4_3, connection)


Среднее значение для нижней грани  Среднее значение для верхней гран
0                            71065.0                           110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.


In [26]:
# текст запроса
query_4_4 = f'''SELECT 
    count(id), schedule, employment
FROM
    vacancies
GROUP BY schedule, employment
ORDER BY count(id) desc
'''

In [27]:
# результат запроса
result_4_4 = pd.read_sql_query(query_4_4, connection)
result_4_4

# На втором месте по популярности Удаленная работа с полной занятостью.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/3961283977.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_4_4 = pd.read_sql_query(query_4_4, connection)


count          schedule           employment
0   35367       Полный день     Полная занятость
1    7802  Удаленная работа     Полная занятость
2    1593     Гибкий график     Полная занятость
3    1312  Удаленная работа  Частичная занятость
4     940    Сменный график     Полная занятость
5     569       Полный день           Стажировка
6     367    Вахтовый метод     Полная занятость
7     347       Полный день  Частичная занятость
8     312     Гибкий график  Частичная занятость
9     141       Полный день     Проектная работа
10    133  Удаленная работа     Проектная работа
11    116     Гибкий график           Стажировка
12    101    Сменный график  Частичная занятость
13     64  Удаленная работа           Стажировка
14     18     Гибкий график     Проектная работа
15     12    Сменный график           Стажировка
16      2    Вахтовый метод     Проектная работа
17      1    Сменный график     Проектная работа

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта. 

In [28]:
# текст запроса
query_4_5 = f'''SELECT 
    count(id), experience
FROM
    vacancies
WHERE experience is not null
GROUP BY experience
ORDER BY count(id)
'''

In [29]:
# результат запроса: самый часто встречающийся запрос необходимого опыта работы - от 1 года до 3 лет, 
# затем от 3 до 6 лет. 
# На третьем месте по популярности вакансии, на которые могут взять кандидата без опыта работы. 
# Наименее популярный требуемый опыт работы - более 6 лет.

result_4_5 = pd.read_sql_query(query_4_5, connection)
result_4_5

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/212014282.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_4_5 = pd.read_sql_query(query_4_5, connection)


count          experience
0   1337         Более 6 лет
1   7197           Нет опыта
2  14511       От 3 до 6 лет
3  26152  От 1 года до 3 лет

# выводы по детальному анализу вакансий
Совершенно логичная взаимосвязь прослеживается в том, как численность населения города, в котором работодатель хочет найти специалиста влияет на количество вакансий в этом городе. В крупных городах часто расположены филиалы крупных компаний, для комплектации штата которого неоьходимо приивлечения большого количества сотрудников. Так же, возможно в крупных городах более сильная текучка кадров.

Из 49 197 вакансий информация о зарплате (хотя бы одна из границ: нижняя или верхняя) есть только в 24 073 вакансиях.
Причин тому может быть несколько: слишком много факторов для конкретного работодателя могут повлиять на уровень заработной платы, которую он готов предложить. Вероятно, слишком широкий диапазон может смутить соискателя. В таком случае было бы лучше сказать об уровне заработной платы после прохождения собеседования или в ответ на отправленное резюме соискателя.
Другой причиной может быть желание начать с кандидатом диалог, в ходе которого рекрутер может с большей уверенностью отказать в собеседовании или наоборот назначить встречу, нежели просто при просмотре резюме, не тратив время на личную встречу.
Еще одной возможной причиной может быть планирование ввести в компании новую должность. Таким образом, можно проанализировать портрет кандидатов, которые интресуются данной позицией, понимать на какую заработную плату они рассчитывают. Вероятно, это не самый популярный способ для того, чтобы сформировать портрет кандидата и его финансовые ожидания, но возможный.
Говоря о конкретных цифрах, можно отметить, что средняя нижняя граница находится на уровне 71 065 руб., а верхняя средняя граница = 110 537 руб.

Говоря о типе занятости и графике работы, можно отметить, что на третьем месте по популярности - гибкий график при полной заятости.
На втором месте, с отрывом в 4,8 раз - вакансии, которые предполагают удаленную работу при полной занятости.
На первом месте, с отрываом в 4,5 раза лидирует полный рабочий день и полная занятость.
Вероятно, на это влияет как специфика работы (важно ли физическое присутствие специалиста), так и предпочтительный для работордателя формат работы (при удаленной работе нет издержек на содержание офисов и тд), или требуемый результат работы: например, когда важно только достижение конкретной цели, большая свобода в виде гибкого графика, вероятно может положительно сказаться на результа и сказаться на привлекательности жтой вакансии для кандидата.

В большей части вакансий требуемый опыт работы - от 1 года до 3 лет. 
Но втором месте по полуряности  - необходимый опыт работы от 3 до 6 лет.
На третьем месте по количеству вакансий находятся позиии, на которые работодатели готовы взять сотрудников без опыта работы. 
На четвертом месте - необходимый опыт работы более 6 лет. 
Это можно объяснить тем, что на более высокую должность невозможо взять специалиста без опыта работы или даже с минимальным опытом. Однако, руководящих позиций обычно меньше, чем открытых вакансий для специалистов, которых в зависимости от профессиональной области можно обучить с нуля или же взять специалиста с небольшим опытом работы.

***

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [30]:
query5_1 = f'''SELECT 
    employers.name as name, count(vacancies.id) as vacancies
FROM 
    vacancies left join employers on vacancies.employer_id = employers.id
GROUP BY employers.name
ORDER BY count(vacancies.id) desc
LIMIT 5
'''

In [31]:
# результат запроса
result5_1 = pd.read_sql_query(query5_1, connection)
result5_1

#По количеству вакансий на первом месте находится Яндекс, а на пятом месте находится Газпром нефть.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_3298/2306165267.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result5_1 = pd.read_sql_query(query5_1, connection)


name  vacancies
0         Яндекс       1933
1     Ростелеком        491
2       Тинькофф        444
3           СБЕР        428
4  Газпром нефть        331

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.


In [8]:
query_5_2_1 = f'''SELECT
    a.name as area, count(distinct e.id) as cnt_emp, count(distinct v.id) as cnt_vac
FROM 
    areas a
    join employers e on e.area = a.id
    join vacancies v on v.area_id = a.id
GROUP BY a.id
ORDER BY cnt_emp desc
'''

result_5_2_1 = pd.read_sql_query(query_5_2_1, connection)
result_5_2_1

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_1532/1952549832.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_5_2_1 = pd.read_sql_query(query_5_2_1, connection)


area  cnt_emp  cnt_vac
0             Москва     5864     5333
1    Санкт-Петербург     2217     2851
2              Минск     1115     2112
3             Алматы      721     1892
4       Екатеринбург      609     1698
..               ...      ...      ...
463       Рассказово        1        1
464          Донской        1        3
465          Ефремов        1        4
466          Кимовск        1        2
467         Невьянск        1        1

[468 rows x 3 columns]

In [9]:
query_5_2_2 = f'''select a.name as area, count(distinct e.id) as employers_amount, count(distinct v.id) as vac_amount
from
    areas a
    left join employers e on e.area = a.id
    left join vacancies v on v.area_id = e.area 
where v.id is null
group by a.name
order by 2 desc
'''

In [10]:
# результат запроса
result_5_2_2 = pd.read_sql_query(query_5_2_2, connection)
result_5_2_2

# В результате получаем, что регион, в котором нет вакансий, наибольший по количеству работодателей - Россия.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_1389/3250244395.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_5_2_2 = pd.read_sql_query(query_5_2_2, connection)


area  employers_amount  vac_amount
0                   Россия               410           0
1                Казахстан               207           0
2       Московская область                75           0
3       Краснодарский край                19           0
4                 Беларусь                18           0
..                     ...               ...         ...
889                Жабинка                 0           0
890  Железногорск-Илимский                 0           0
891                Жетысай                 0           0
892               Жигалово                 0           0
893               Жирновск                 0           0

[894 rows x 3 columns]

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.


In [6]:
# текст запроса
query_5_3 = f'''SELECT 
employer_id, count(distinct area_id)
FROM vacancies
GROUP BY employer_id
ORDER BY 2 desc
'''

In [7]:
# результат запроса
result_5_3 = pd.read_sql(query_5_3, connection)
result_5_3

# В результате запроса узнаем, что максимальное количество регионов, в котором работодатель публикует свои вакансии - 181.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_1389/3334885135.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_5_3 = pd.read_sql(query_5_3, connection)


employer_id  count
0             1740    181
1             2748    152
2          5724811    116
3          5130287     88
4          3682876     71
...            ...    ...
14901       810278      1
14902       810313      1
14903       810551      1
14904       810688      1
14905       811902      1

[14906 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности. 

In [7]:
# текст запроса
query_5_4 = f'''SELECT count(e.id)
FROM 
    employers e
    left join employers_industries ei on e.id = ei.employer_id
WHERE industry_id is null
'''

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_1532/3711328211.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_5_4 = pd.read_sql_query(query_5_4, connection)


count
0   8419

In [ ]:
# результат запроса
result_5_4 = pd.read_sql_query(query_5_4, connection)
result_5_4

# В результате выполнения запроса получаем, что у 8419 работодателей не указана сфера деятельности.

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности. 

In [29]:
# текст запроса
query_5_5 = f'''SELECT e.name
FROM employers e left join employers_industries ei on e.id = ei.employer_id
GROUP BY e.name
HAVING count(ei.industry_id) = 4
ORDER BY e.name
OFFSET 2
LIMIT 1
'''

In [30]:
# результат запроса
result_5_5 = pd.read_sql_query(query_5_5, connection)
result_5_5

# Ответ: "2ГИС"

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_1532/461755949.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_5_5 = pd.read_sql_query(query_5_5, connection)


name
0  2ГИС

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.


In [40]:
# текст запроса
query_5_6 = f'''SELECT count(i.name)
FROM employers_industries ei left join industries i on ei.industry_id = i.id
WHERE i.name LIKE 'Разработка программного обеспечения'
'''


In [41]:
# результат запроса
result_5_6 = pd.read_sql_query(query_5_6, connection)
result_5_6

# У 3553 работодателей 'Разработка программного обеспечения' указана как сфера их деятельности.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_1532/2006184108.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_5_6 = pd.read_sql_query(query_5_6, connection)


count
0   3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API. 

In [80]:
# код для получения списка городов-милионников
import requests
from bs4 import BeautifulSoup

url = 'https://ru.wikipedia.org/wiki/Города-миллионеры_России'
response = requests.get(url)
page = BeautifulSoup(response.text, 'html.parser')

cities = str(page.find('table', class_ = 'standard'))
cities = cities.split('title="')[3:]
million_cities = []
for i in cities:
    million_cities.append(i.split('">')[0])

million_cities = tuple(million_cities)
print(million_cities)


('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Казань', 'Нижний Новгород', 'Красноярск', 'Челябинск', 'Самара', 'Уфа', 'Ростов-на-Дону', 'Краснодар', 'Омск', 'Воронеж', 'Пермь', 'Волгоград')


In [198]:
# текст запроса

query_5_7 = f'''with abc as 
(SELECT
    a.name as name, count(distinct v.id) as cnt
FROM
    vacancies v
    join areas a on area_id = a.id
    join employers e on v.employer_id = e.id
WHERE
    (e.name LIKE 'Яндекс') and (a.name in {million_cities})
GROUP BY a.id
ORDER BY cnt)


(SELECT *
FROM abc)

UNION ALL

(SELECT
    'total', sum(cnt) as total
FROM abc) 
'''

In [199]:
# результат запроса
result_5_7 = pd.read_sql_query(query_5_7, connection)
result_5_7

#Всего в городах-миллионниках Яндекс разместил 485 вакансий, при этом на Москву пришлось 54 вакансии, а на Омск более чем в два раза меньше - всего 21 вакансия.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_1128/786645949.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_5_7 = pd.read_sql_query(query_5_7, connection)


name    cnt
0              Омск   21.0
1         Челябинск   22.0
2        Красноярск   23.0
3         Волгоград   24.0
4    Ростов-на-Дону   25.0
5            Казань   25.0
6             Пермь   25.0
7            Самара   26.0
8               Уфа   26.0
9         Краснодар   30.0
10          Воронеж   32.0
11      Новосибирск   35.0
12  Нижний Новгород   36.0
13     Екатеринбург   39.0
14  Санкт-Петербург   42.0
15           Москва   54.0
16            total  485.0

***

# выводы по анализу работодателей
В топ-5 по количеству размещенных вакансий попали такие работодатели как Яндекс, Ростелеком, Тинькофф, СБЕР, Газпром. 
При этом, занимая первое место, Яндекс разместил в 3,9 раз больше вакансий, чем второй по популярности Ростелеком. Только в городах-миллионниках "Яндекс" разместил 485 вакансий. При этом лидирующее количество вакансий, конечно же, в Москве.

Говоря про количество вакансий в регионах в общем, можно отметить, что самый популярный город - Москва, затем Санкт-Петербург (в СПБ вакансий в 1,9 раз меньше, чем в Москве).
В зависимости от масштаба компаниии, варьируется количество регионов, в котором работодатель ищет сотрудников (от 1 до 181 региона на одного работодателя).
У 36% работодателей не указана сфера их деятельности.

У 3553 (15% от общего количества) работодателей 'Разработка программного обеспечения' указана как сфера их деятельности.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.* 


In [29]:
# текст запроса
query_6_1 = f'''SELECT count(v.id)
FROM vacancies v 
WHERE (v.name ILIKE '%data%') or (v.name ILIKE '%данн%')
'''

In [30]:
# результат запроса
result_6_1 = pd.read_sql_query(query_6_1, connection)
result_6_1

# 1771 вакансия имеет отношение к данным.


/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_803/4032184885.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_6_1 = pd.read_sql_query(query_6_1, connection)


count
0   1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.
 

In [60]:
# текст запроса
query_6_2 = f'''SELECT count(*)
FROM vacancies v
WHERE ((v.name ILIKE '%data scientist%') OR 
(v.name ILIKE '%data science%') OR 
(v.name ILIKE '%исследователь данных%') OR 
(v.name ILIKE '%machine learning%') OR 
(v.name ILIKE '%машинн%обучен%') OR 
((v.name LIKE '%ML%') AND (v.name NOT LIKE '%HTML%'))) AND
((v.name ILIKE '%junior%') OR
(v.experience ILIKE 'Нет опыта') OR 
(v.employment ILIKE 'Стажировка'))
'''


In [61]:
# результат запроса
result_6_2 = pd.read_sql_query(query_6_2, connection)
result_6_2

# 51 вакансия из нашей базы подходит для начинающего дата-сайентиста.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_803/2865164135.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_6_2 = pd.read_sql_query(query_6_2, connection)


count
0     51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [66]:
# текст запроса
query_6_3 = f'''SELECT count(*)
FROM vacancies v
WHERE ((v.name ILIKE '%data scientist%') OR 
(v.name ILIKE '%data science%') OR 
(v.name ILIKE '%исследователь данных%') OR 
(v.name ILIKE '%machine learning%') OR 
(v.name ILIKE '%машинн%обучен%') OR 
((v.name LIKE '%ML%') AND (v.name NOT LIKE '%HTML%'))) AND
((v.key_skills ILIKE '%SQL%') or (v.key_skills ILIKE '%postgres%'))
'''


/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_803/3555502865.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_6_3 = pd.read_sql_query(query_6_3, connection)


count
0    201

In [ ]:
# результат запроса
result_6_3 = pd.read_sql_query(query_6_3, connection)
result_6_3

# В базе с резюме есть 201 вакансия для DS, в которых в качестве ключевого навыка указан SQL или postgres.

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [67]:
# текст запроса
query_6_4 = f'''SELECT count(*)
FROM vacancies v
WHERE ((v.name ILIKE '%data scientist%') OR 
(v.name ILIKE '%data science%') OR 
(v.name ILIKE '%исследователь данных%') OR 
(v.name ILIKE '%machine learning%') OR 
(v.name ILIKE '%машинн%обучен%') OR 
((v.name LIKE '%ML%') AND (v.name NOT LIKE '%HTML%'))) AND
(v.key_skills ILIKE '%python%')
'''


In [69]:
# результат запроса
result_6_4 = pd.read_sql_query(query_6_4, connection)
result_6_4

# В 351 вакансии Python указан в качестве ключевого навыка.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_803/1790783851.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_6_4 = pd.read_sql_query(query_6_4, connection)


count
0    351

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [105]:
# текст запроса
query_6_5 = f'''SELECT ROUND(AVG((length(v.key_skills) - length(replace(v.key_skills, CHR(9), ''))) + 1), 2)


FROM vacancies v
WHERE ((v.name ILIKE '%data scientist%') OR 
(v.name ILIKE '%data science%') OR 
(v.name ILIKE '%исследователь данных%') OR 
(v.name ILIKE '%machine learning%') OR 
(v.name ILIKE '%машинн%обучен%') OR 
((v.name LIKE '%ML%') AND (v.name NOT LIKE '%HTML%'))) AND
v.key_skills IS NOT NULL
'''

In [106]:
# результат запроса
result_6_5 = pd.read_sql_query(query_6_5, connection)
result_6_5

# В среднем указывают в вакансиях для DS указывают 6 ключевых навыков.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_803/878557823.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_6_5 = pd.read_sql_query(query_6_5, connection)


round
0   6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа. 

In [168]:
# текст запроса
query_6_6 = f'''SELECT v.experience, ROUND(AVG(coalesce(((v.salary_from+v.salary_to)/2), v.salary_from, v.salary_to))) as result
FROM vacancies v
WHERE ((v.name ILIKE '%data scientist%') OR 
(v.name ILIKE '%data science%') OR 
(v.name ILIKE '%исследователь данных%') OR 
(v.name ILIKE '%machine learning%') OR 
(v.name ILIKE '%машинн%обучен%') OR 
((v.name LIKE '%ML%') AND (v.name NOT LIKE '%HTML%'))) AND
((v.salary_from is not null) or (v.salary_to is not null))
GROUP BY v.experience
'''

In [169]:
# результат запроса
result_6_6 = pd.read_sql_query(query_6_6, connection)
result_6_6

# 243 115 руб. - средний уровень заработной платы, на который может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет.

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_803/4066043572.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_6_6 = pd.read_sql_query(query_6_6, connection)


experience    result
0           Нет опыта   74643.0
1  От 1 года до 3 лет  139675.0
2       От 3 до 6 лет  243115.0

# выводы по предметному анализу
Говоря о вакансиях, имеющих отношение к данным, можно отметить, что в этой области ищут 1771 специалиста. 
Из них 51 вакансия подходит для начинающего дата-сайентиста.
В 201 вакансии для DS, в которых в качестве ключевого навыка указан SQL или postgres.
В 351 вакансии Python указан в качестве ключевого навыка.

В среднем указывают в вакансиях для DS указывают 6 ключевых навыков.

А уровень заработной платы DS специалиста варьируется в зависимости от опыта его работы:
- специалист без опыта в среднем может рассчитывать на зп около 75 тысяч рублей.
- DS с опытом работы от 1 до 3 лет может получать в среднем около 140 тысяч рублей.
- дата-сайентист с опытом работы от 3 до 6 лет может претендовать на заработную плату в среднем в 243 тысячи рублей.

***

# Дополнительные исследования

In [173]:
# Выведем топ основных ключевых навыков, нужных DS специалисту.

query01 = f'''with sep_skills as (SELECT unnest(string_to_array(v.key_skills, '\t')) AS skill
FROM vacancies v
WHERE ((v.name ILIKE '%data scientist%') OR 
(v.name ILIKE '%data science%') OR 
(v.name ILIKE '%исследователь данных%') OR 
(v.name ILIKE '%machine learning%') OR 
(v.name ILIKE '%машинн%обучен%') OR 
((v.name LIKE '%ML%') AND (v.name NOT LIKE '%HTML%'))) AND
v.key_skills IS NOT NULL)

SELECT skill, count(skill)
FROM sep_skills
GROUP BY skill
ORDER BY count desc
LIMIT 20
'''

result01 = pd.read_sql_query(query01, connection)
result01

# ТОП (по частоте их указания в резюме) основных навыков, необходимых DS специалисту по мнению работодателей, это:
# Python (указан в 72,5% вакансий для DS спецйиалиста),
# SQL (указан в 40%),
# Machine Learning (24%),
# Git (14%)

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_8714/712737893.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result01 = pd.read_sql_query(query01, connection)


skill  count
0                         Python    348
1                            SQL    191
2               Machine Learning    114
3                            Git     66
4      Математическая статистика     62
5                  Data Analysis     54
6                         Pandas     52
7                   Data Science     52
8                             ML     49
9                Английский язык     48
10                         Linux     47
11                       PyTorch     46
12                 Анализ данных     46
13                      Big Data     42
14  Математическое моделирование     41
15         Статистический анализ     40
16                           NLP     40
17                           C++     39
18                         Spark     38
19                    Tensorflow     35

In [151]:
# Зависимости количества необходимых навыков от уровня предлагаемой средней заработной платы.

query02 = f'''SELECT (length(v.key_skills) - length(replace(v.key_skills, CHR(9), '')) + 1) as skills_amount, ROUND(AVG(coalesce(((v.salary_from+v.salary_to)/2), v.salary_from, v.salary_to))) as salary


FROM vacancies v
WHERE ((v.name ILIKE '%data scientist%') OR 
(v.name ILIKE '%data science%') OR 
(v.name ILIKE '%исследователь данных%') OR 
(v.name ILIKE '%machine learning%') OR 
(v.name ILIKE '%машинн%обучен%') OR 
((v.name LIKE '%ML%') AND (v.name NOT LIKE '%HTML%'))) AND
v.key_skills IS NOT NULL
GROUP BY skills_amount
ORDER BY salary desc NULLS LAST
'''

result02 = pd.read_sql_query(query02, connection)
result02

# Нет прямой зависимости роста зп от количества указанных навыков

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_8714/4263707268.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result02 = pd.read_sql_query(query02, connection)


skills_amount    salary
0               4  333333.0
1              14  300000.0
2               2  225000.0
3               3  206349.0
4              16  205000.0
5               5  191078.0
6              12  175346.0
7               6  170471.0
8               8  161786.0
9               7  143500.0
10             10  112500.0
11              9  108563.0
12             11   82262.0
13             20       NaN
14             13       NaN
15             15       NaN
16             17       NaN
17             19       NaN
18              1       NaN

In [37]:
# Соответствие среднего уровня заработной платы от профессиональной области, должности.

query03 = f'''SELECT i.name as industry, ROUND(AVG(coalesce(((v.salary_from+v.salary_to)/2), v.salary_from, v.salary_to))) as salary
FROM vacancies v 
join employers_industries ei on v.employer_id = ei.employer_id
join industries i on ei.industry_id = i.id
GROUP BY i.name
ORDER BY salary desc NULLS LAST
LIMIT 10
'''

result03 = pd.read_sql_query(query03, connection)
display(result03)

query03_1 = f'''SELECT  v.name as position, i.name as industry, ROUND(AVG(coalesce(((v.salary_from+v.salary_to)/2), v.salary_from, v.salary_to))) as salary
FROM vacancies v 
join employers_industries ei on v.employer_id = ei.employer_id
join industries i on ei.industry_id = i.id
GROUP BY v.name, i.name
ORDER BY salary desc NULLS LAST
LIMIT 40
'''

result03_1 = pd.read_sql_query(query03_1, connection)
result03_1

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_8714/278499866.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result03 = pd.read_sql_query(query03, connection)


industry    salary
0          Агрохимия (продвижение, оптовая торговля)  381429.0
1                           Агрохимия (производство)  339875.0
2                                     Игорный бизнес  191905.0
3                  Корма для животных (производство)  168300.0
4                                         Зоомагазин  167613.0
5                                 Кадровые агентства  144530.0
6      Лакокрасочная продукция, сырье (производство)  142803.0
7  Бытовая химия, парфюмерия, косметика  (произво...  130120.0
8  Лакокрасочная продукция, сырье (продвижение, о...  128445.0
9  Дорожно-строительная техника, сельскохозяйстве...  122878.0

/var/folders/14/w5z30cwx541gq2kzys9tvttc0000gn/T/ipykernel_8714/278499866.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result03_1 = pd.read_sql_query(query03_1, connection)


position  \
0                          СТО/Директор по разработке   
1                          СТО/Директор по разработке   
2                          СТО/Директор по разработке   
3                      Брокер по продаже апартаментов   
4                      Брокер по продаже апартаментов   
5                          СТО/Директор по разработке   
6                              QA Automation Engineer   
7              Директор по информационным технологиям   
8                     Руководитель команды разработки   
9                     Руководитель команды разработки   
10                    Руководитель команды разработки   
11                    Руководитель команды разработки   
12  Senior Software Developer (upwork / иностранны...   
13  Senior Software Developer (upwork / иностранны...   
14                        Chief Product Officer (CPO)   
15                       Директор IT (HoReCa, Retail)   
16                       Директор IT (HoReCa, Retail)   
17                           Project/Delivery manager   
18                           Project/Delivery manager   
19                           Project/Delivery manager   
20                           Project/Delivery manager   
21                           Project/Delivery manager   
22                            Product manager LATOKEN   
23                Руководитель Отдела тестирования/QA   
24                            Программист-разработчик   
25                            Программист-разработчик   
26  Директор научно-исследовательского центра (химия)   
27  Директор научно-исследовательского центра (химия)   
28  Директор научно-исследовательского центра (химия)   
29                    Java Backend Developer (remote)   
30  Директор научно-исследовательского центра (химия)   
31  Java-разработчик (со 2-ой формой допуска к гос...   
32  Java-разработчик (со 2-ой формой допуска к гос...   
33                                     Lead of Mobile   
34                       ML Engineer \ Data scientist   
35                       ML Engineer \ Data scientist   
36         Lead ETL разработчик (Phyton) / Архитектор   
37         Lead ETL разработчик (Phyton) / Архитектор   
38         Lead ETL разработчик (Phyton) / Архитектор   
39                           Liquidity Bots Developer   

                                             industry    salary  
0                                    Интернет-магазин  750000.0  
1   Полуфабрикаты, в том числе замороженные (произ...  750000.0  
2                 Разработка программного обеспечения  750000.0  
3                   Консалтинг, оценка в недвижимости  750000.0  
4                     Агентские услуги в недвижимости  750000.0  
5              Розничная сеть (DIY и товары для дома)  750000.0  
6   Интернет-компания (поисковики, платежные систе...  700000.0  
7                                  Кадровые агентства  650000.0  
8                                  Кадровые агентства  600000.0  
9   Системная интеграция,  автоматизации технологи...  600000.0  
10                              Консалтинговые услуги  600000.0  
11                Разработка программного обеспечения  600000.0  
12                Разработка программного обеспечения  555261.0  
13  Системная интеграция,  автоматизации технологи...  555261.0  
14  Интернет-компания (поисковики, платежные систе...  550000.0  
15                              Консалтинговые услуги  550000.0  
16                                 Кадровые агентства  550000.0  
17  Интернет-компания (поисковики, платежные систе...  546087.0  
18  Системная интеграция,  автоматизации технологи...  546087.0  
19                                 Кадровые агентства  546087.0  
20  Научно-исследовательская, научная, академическ...  546087.0  
21                Разработка программного обеспечения  546087.0  
22  Финансово-кредитное посредничество (биржа, бро...  526638.0  
23                                 Кадровые агентства  500000.0  
24                             Строительство жилищное  50

Выводы по дополнительным исследованиям

В качестве дополнительгных ислледований, опираясь на собственную заинтересованность, я хотела оценить какие ключевые новыки нужны DS специалисту, и как влияет количество этих навыков на уровень заработной платы.

Так же, интересно было посмотреть на картину в общем: как влияет регион и профессиональная сфера деятельности на уровень заработной платы.

По итогам проведенных исследований, можно сказать, что ожидаемой прямопропорциональной зависимости уровня заработной платы от количества необходимых ключевых навыков не наблюдается. В вакансиях, с самым низким среднем уровенем зп (из указанных) указано 11 ключевых навыков, тогда как для самого выского среднего уровня зп - 4 ключевых навыка. 
Вероятно это происходит потому, что при составлении вакансии часть компаний указывала не только навыки владения конкретными продуктами или языками, но и такие общие характеристики как "Математический анализ", "Работа в команде" и т.д. Это, в целом, полезная информация для соискателя, но практически сложно проверяемая рекрутером. Возможно поэтому и не часто останавливающая соискателя, не обладающего нужными общими навыками, от отклика на вакансию.

Перейдем к конкретным навыкам, которые в основном требуют работодатели от соискателей, рассчитывающих на должность DS специалиста. Топ выглядит следующим образом: Python, SQL, Machine Learning, а так же навыки матиматического и статистического анализа, навыки работы с Git. Так же упоминаются Pandas, ML, Linux, C++.

Таким образом, мы знаем какими ключевыми навыками должен обладать дата сайентист. Однако стоит проверить нет ли среди "не топовых" (по количеству вхождений в нашу базу навыков) навыков, редких, но весомых. Ведь часто специалист в узкой области ценится довольно высоко. 
Отсортировов результат запроса по возрастанию, увидим, что есть специфические для DS навыки, например такие как ERP и Kubernetis, но вполне обоснованные для специалиста, занимающегося планированием ресурсов предприятия и кластерами.

Анализируя зависимость заработной платы от сферы деятельности компании, сложно сделать однозначные выводы, так как данные слишком обобщены - топ 3 результата в этой выборке: агрохимия (оптовая торговля и продвижение) и игорный близнес. Какие позиции (предлогаемые вакансии) привели эти сферы деятельности к алимпу выборки - не понятно, поэтому я решила посмотреть не только на сферу деятельности компании, но и на предлогаемую позицию.
Выводы из этой заивисимости сделать проще: как ожидалось, самые высокооплачивыаемые позиции у директоров, руководителей, senior специалистов. Безусловно, брокер по продаже недвижимости с "потолком зп, который может поставить себе только он" всегда где-то рядом с руководящими должностями :).
В целом, говоря о сферах деятельности компании (топ 40 по уровню среднгей зп), можно отметить, что они совершенно разные: от компаний, занимающимися производством полуфабрикатов, до строительства. Однако главную зависимость видно четко: в основном эти компании ищут опытных специалистов сферы IT, которым готовы хорошо платить.

***

# Общий вывод по проекту

# подведем итог исследования, обобщите выводы

Подводя итоги исследований вакакнсий с hh, можно сказать о том, что наблюдается четкая взаимосвязь между количеством вакансий 
и численности населения города, в котором требуется определенный специалист. Чем крупнее город - тем больше выбор вакансий, а так же выше предлогаемая зп.
В крупных городах заработная плата более чем в 13 раз больше, чем в мелких городах. Безуcловно, на это может влиять как уровень образования в отдаленных, маленьких городах, как следствие и компетенция специалистов. Так же еще одним фактором может выступать общий уровень цен (в центральном регионе, особенно крупных городах, цены могут быть выше). Расположение филиалов крупных компаний, которым требуются много сотрудников при адекватном предложении заработной платы, как правильно, приходится на более крпуные города. 
Вероятно, эту проблему можно решить путем повышения уровня образования населения маленьких городов, при необходимости построив там учебные учреждения. 
Так же появление филиалов крупных компаний в маленьких городах может помочь сократить столь весомую разницу в зп и количестве вакансий.


Более чем в 50% вакансий не указана хотя бы одна из границ заработной платы. Я считаю этот критерий достаточно важным для того, чтобы на месте соискателя отсеить часть вакансий, зп в которых мне не подходит. Для рекрутера это может быть экономией времени, потраченной на кандидата, который в итоге не захочет устраиваться на работу. В маленьких компаниях обязанности рекрутера часто лежат на руководителях, тогда вопрос об экономии времени становится еще большее актуальным. 

Полная занятость - самый популярный тип занятости. Для многих компаний и дожностей приемлим только такой рабочий график, но если компания рассматривает возможность привлечения людей на не полный рабочий день (пересчитав, например, возможную зарплату, в соотвтетствии с рабочем временем), потенциальных сотрудников становится намного боольше: ведь часто студенты готовы и способны работать и приносить пользу компании.

На сайте hh соискателю доступен поиск вакансий по отрасли компании. У 36% работодателей не указана сфера их деятельности, что может приводить к тому, что вакансии этих компаний не видны части соискателей. 
Помимо этого, дело в элементрном удобстве: при просмотре вакансии не нужно лезть в поиск чтобы посмотреть чем занмиается компания, вакансия которой заинтересовала.
Возможно, если проанализировать скорость найма сотрудников и количество отзыввов на их вакансии, это может стимулировать компании заполнять бошльше информации о себе.

Говоря о вакансиях, имеющих отношение к данным, можно отметить, что у 15% работодателей 'Разработка программного обеспечения' указана как сфера их деятельности. В этой области предложена 1771 вакансия. Из них 51 вакансия подходит для начинающего дата-сайентиста.

В 201 вакансии для DS, в которых в качестве ключевого навыка указан SQL или postgres.
В 351 вакансии Python указан в качестве ключевого навыка. Вероятно, популярность Python набирает обороты.

В среднем указывают в вакансиях для DS указывают 6 ключевых навыков.

Заработная плата DS специалиста варьируется в среднем от 75 тысяч рублей (специалист без опыта работы) до 243 тысячь рублей в среднем для специалиста, чей стаж составляет от 3 до 6 лет.

По результатам дополнительных исследований можно отметить, что сфера IT является одной из самых высокооплачиваемых. В ней так же прослеживается логичная закономерность: чем опытнее специалист и чем больше у него навыков, тем выше может быть уровень его дохода.